-- +goose Up
ALTER TABLE reports 
ALTER COLUMN reporter_name DROP NOT NULL,
ALTER COLUMN reporter_role DROP NOT NULL,
ALTER COLUMN village DROP NOT NULL,
ALTER COLUMN district DROP NOT NULL,
ALTER COLUMN building_name DROP NOT NULL,
ALTER COLUMN building_type DROP NOT NULL,
ALTER COLUMN report_status DROP NOT NULL,
ALTER COLUMN funding_source DROP NOT NULL,
ALTER COLUMN created_at DROP NOT NULL,
ALTER COLUMN updated_at DROP NOT NULL;

-- +goose Down
ALTER TABLE reports 
ALTER COLUMN reporter_name SET NOT NULL,
ALTER COLUMN reporter_role SET NOT NULL,
ALTER COLUMN village SET NOT NULL,
ALTER COLUMN district SET NOT NULL,
ALTER COLUMN building_name SET NOT NULL,
ALTER COLUMN building_type SET NOT NULL,
ALTER COLUMN report_status SET NOT NULL,
ALTER COLUMN funding_source SET NOT NULL,
ALTER COLUMN created_at SET NOT NULL,
ALTER COLUMN updated_at SET NOT NULL;