package seeds

import (
	"building-report-backend/internal/domain/entity"
	"building-report-backend/pkg/utils"
	"gorm.io/gorm"
	"time"
)

func SeedBinaMarga(db *gorm.DB) error {
	// Get first user as CreatedBy
	var firstUser entity.User
	if err := db.First(&firstUser).Error; err != nil {
		return err
	}

	reports := []entity.BinaMargaReport{
		{
			ID:                     utils.GenerateULID(),
			ReporterName:           "Tri Wahyono",
			InstitutionUnit:        entity.InstitutionUnitDinas,
			PhoneNumber:            "081234567890",
			ReportDateTime:         time.Now().AddDate(0, 0, -5),
			RoadName:               "Jl. Raya Ngawi-Madiun",
			RoadType:               entity.RoadTypeJalanProvinsi,
			RoadClass:              entity.RoadClassArteri,
			SegmentLength:          500.0,
			Latitude:               -7.4040,
			Longitude:              111.4464,
			PavementType:           entity.PavementAspalFlexible,
			DamageType:             entity.RoadDamageLubang,
			DamageLevel:            entity.RoadDamageLevelSevere,
			DamagedLength:          25.0,
			DamagedWidth:           3.5,
			DamagedArea:            87.5,
			TotalDamagedArea:       87.5,
			TrafficCondition:       entity.TrafficConditionOneLane,
			TrafficImpact:          entity.TrafficImpactSeverelyReduced,
			DailyTrafficVolume:     15000,
			UrgencyLevel:           entity.RoadUrgencyEmergency,
			CauseOfDamage:          "Beban kendaraan berat dan cuaca ekstrem saat musim hujan",
			Status:                 entity.BinaMargaStatusPending,
			Notes:                  "Jalan arteri utama menuju Madiun, perlu penanganan segera",
			EstimatedBudget:        125000000,
			EstimatedRepairTime:    14,
			CreatedBy:              firstUser.ID,
			CreatedAt:              time.Now().AddDate(0, 0, -5),
			UpdatedAt:              time.Now().AddDate(0, 0, -5),
		},
		{
			ID:                     utils.GenerateULID(),
			ReporterName:           "Dewi Kusuma",
			InstitutionUnit:        entity.InstitutionUnitKecamatan,
			PhoneNumber:            "082345678901",
			ReportDateTime:         time.Now().AddDate(0, 0, -10),
			RoadName:               "Jl. Paron Raya",
			RoadType:               entity.RoadTypeJalanKabupaten,
			RoadClass:              entity.RoadClassKolektor,
			SegmentLength:          300.0,
			Latitude:               -7.3950,
			Longitude:              111.4350,
			PavementType:           entity.PavementAspalFlexible,
			DamageType:             entity.RoadDamageRetakBuaya,
			DamageLevel:            entity.RoadDamageLevelModerate,
			DamagedLength:          80.0,
			DamagedWidth:           4.0,
			DamagedArea:            320.0,
			TotalDamagedArea:       320.0,
			TrafficCondition:       entity.TrafficConditionNormal,
			TrafficImpact:          entity.TrafficImpactMinimal,
			DailyTrafficVolume:     8000,
			UrgencyLevel:           entity.RoadUrgencyHigh,
			CauseOfDamage:          "Penurunan tanah dan sistem drainase yang kurang memadai",
			Status:                 entity.BinaMargaStatusVerified,
			Notes:                  "Perlu perbaikan lapisan permukaan jalan",
			HandlingRecommendation: "Overlay asphalt dan perbaikan sistem drainase",
			EstimatedBudget:        85000000,
			EstimatedRepairTime:    10,
			CreatedBy:              firstUser.ID,
			CreatedAt:              time.Now().AddDate(0, 0, -10),
			UpdatedAt:              time.Now().AddDate(0, 0, -3),
		},
		{
			ID:                     utils.GenerateULID(),
			ReporterName:           "Ahmad Firdaus",
			InstitutionUnit:        entity.InstitutionUnitDesa,
			PhoneNumber:            "083456789012",
			ReportDateTime:         time.Now().AddDate(0, 0, -3),
			RoadName:               "Jl. Desa Geneng",
			RoadType:               entity.RoadTypeJalanDesa,
			RoadClass:              entity.RoadClassLokal,
			SegmentLength:          200.0,
			Latitude:               -7.3800,
			Longitude:              111.4200,
			PavementType:           entity.PavementPaving,
			DamageType:             entity.RoadDamageGenaganDrainase,
			DamageLevel:            entity.RoadDamageLevelModerate,
			DamagedLength:          15.0,
			DamagedWidth:           1.5,
			DamagedArea:            22.5,
			TotalDamagedArea:       22.5,
			TrafficCondition:       entity.TrafficConditionNormal,
			TrafficImpact:          entity.TrafficImpactMinimal,
			DailyTrafficVolume:     3000,
			UrgencyLevel:           entity.RoadUrgencyMedium,
			CauseOfDamage:          "Drainase tersumbat dan overflow saat musim hujan",
			Status:                 entity.BinaMargaStatusPlanned,
			Notes:                  "Sudah masuk program perbaikan rutin tahun ini",
			HandlingRecommendation: "Pembersihan dan normalisasi drainase",
			EstimatedBudget:        12000000,
			EstimatedRepairTime:    5,
			CreatedBy:              firstUser.ID,
			CreatedAt:              time.Now().AddDate(0, 0, -3),
			UpdatedAt:              time.Now().AddDate(0, 0, -3),
		},
		{
			ID:                     utils.GenerateULID(),
			ReporterName:           "Rina Wijayanti",
			InstitutionUnit:        entity.InstitutionUnitDinas,
			PhoneNumber:            "084567890123",
			ReportDateTime:         time.Now().AddDate(0, 0, -15),
			RoadName:               "Jl. Mantingan-Jogorogo",
			RoadType:               entity.RoadTypeJalanKabupaten,
			RoadClass:              entity.RoadClassKolektor,
			SegmentLength:          150.0,
			Latitude:               -7.4100,
			Longitude:              111.4600,
			PavementType:           entity.PavementBetonRigid,
			DamageType:             entity.RoadDamageJembatan,
			DamageLevel:            entity.RoadDamageLevelSevere,
			DamagedLength:          0,
			DamagedWidth:           0,
			DamagedArea:            0,
			TotalDamagedArea:       0,
			BridgeName:             "Jembatan Mantingan 1",
			BridgeStructureType:    entity.BridgeStructureBetonBertulang,
			BridgeDamageType:       entity.BridgeDamageRangkaRetak,
			BridgeDamageLevel:      entity.BridgeDamageLevelSevere,
			TrafficCondition:       entity.TrafficConditionOneLane,
			TrafficImpact:          entity.TrafficImpactSeverelyReduced,
			DailyTrafficVolume:     12000,
			UrgencyLevel:           entity.RoadUrgencyEmergency,
			CauseOfDamage:          "Korosi besi tulangan dan retak struktural pada balok utama",
			Status:                 entity.BinaMargaStatusInProgress,
			Notes:                  "Perbaikan jembatan prioritas tinggi, sudah dalam tahap pelaksanaan",
			HandlingRecommendation: "Perbaikan struktural dan penguatan balok dengan carbon fiber",
			EstimatedBudget:        450000000,
			EstimatedRepairTime:    60,
			CreatedBy:              firstUser.ID,
			CreatedAt:              time.Now().AddDate(0, 0, -15),
			UpdatedAt:              time.Now().AddDate(0, 0, -1),
		},
		{
			ID:                     utils.GenerateULID(),
			ReporterName:           "Hadi Santoso",
			InstitutionUnit:        entity.InstitutionUnitKecamatan,
			PhoneNumber:            "085678901234",
			ReportDateTime:         time.Now().AddDate(0, 0, -1),
			RoadName:               "Jl. Desa Ketanggi",
			RoadType:               entity.RoadTypeJalanDesa,
			RoadClass:              entity.RoadClassLingkungan,
			SegmentLength:          100.0,
			Latitude:               -7.4200,
			Longitude:              111.4500,
			PavementType:           entity.PavementJalanTanah,
			DamageType:             entity.RoadDamageAmblas,
			DamageLevel:            entity.RoadDamageLevelSevere,
			DamagedLength:          30.0,
			DamagedWidth:           3.0,
			DamagedArea:            90.0,
			TotalDamagedArea:       90.0,
			TrafficCondition:       entity.TrafficConditionBlocked,
			TrafficImpact:          entity.TrafficImpactBlocked,
			DailyTrafficVolume:     500,
			UrgencyLevel:           entity.RoadUrgencyEmergency,
			CauseOfDamage:          "Hujan deras dan tanah longsor menutup jalan akses desa",
			Status:                 entity.BinaMargaStatusPending,
			Notes:                  "Jalan akses desa tertutup total, perlu evakuasi material longsor segera",
			HandlingRecommendation: "Pembersihan material longsor dan pengerasan jalan dengan batu split",
			EstimatedBudget:        65000000,
			EstimatedRepairTime:    21,
			CreatedBy:              firstUser.ID,
			CreatedAt:              time.Now().AddDate(0, 0, -1),
			UpdatedAt:              time.Now().AddDate(0, 0, -1),
		},
	}

	for _, report := range reports {
		if err := db.Create(&report).Error; err != nil {
			return err
		}
	}

	return nil
}